In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os


In [2]:
df1= pd.read_excel("Data Preprocessing Data File.xlsx")	
print (df1)


   Country   Age   Salary  Purchased 
0   France   44.0  72000.0         No
1       NaN  27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes


In [4]:
x = df1.iloc [:, :-1].values
x

array([['France ', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany ', nan, 54000.0],
       ['Spain ', 39.0, nan],
       ['Germany ', nan, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, nan],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [5]:
y = df1.iloc [:, -1].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [9]:
x[:,1:2]

array([[44.0],
       [27.0],
       [nan],
       [39.0],
       [nan],
       [35.0],
       [39.0],
       [48.0],
       [50.0],
       [37.0]], dtype=object)

In [12]:
from sklearn.impute import SimpleImputer
si=  SimpleImputer()
x[:,1:2]= si.fit_transform(x[:,1:2])

In [13]:
print (x)

[['France ' 44.0 72000.0]
 [nan 27.0 48000.0]
 ['Germany ' 39.875 54000.0]
 ['Spain ' 39.0 nan]
 ['Germany ' 39.875 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 nan]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [14]:
from sklearn.impute import SimpleImputer
si=  SimpleImputer()
x[:,2:3]= si.fit_transform(x[:,2:3])
x

array([['France ', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany ', 39.875, 54000.0],
       ['Spain ', 39.0, 62250.0],
       ['Germany ', 39.875, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, 62250.0],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [16]:
from sklearn.impute import SimpleImputer
si=  SimpleImputer(strategy='most_frequent')
x[:,0:1]= si.fit_transform(x[:,0:1])
x

array([['France ', 44.0, 72000.0],
       ['France ', 27.0, 48000.0],
       ['Germany ', 39.875, 54000.0],
       ['Spain ', 39.0, 62250.0],
       ['Germany ', 39.875, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, 62250.0],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,0]= le.fit_transform (x[:,0])
print (x)

[[0 44.0 72000.0]
 [0 27.0 48000.0]
 [1 39.875 54000.0]
 [2 39.0 62250.0]
 [1 39.875 64000.0]
 [0 35.0 58000.0]
 [2 39.0 52000.0]
 [0 48.0 62250.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers= [('onehot',OneHotEncoder(), [0] )], remainder = 'passthrough')
x= ct.fit_transform (x)
display (x)


array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 39.875, 54000.0],
       [0.0, 0.0, 1.0, 39.0, 62250.0],
       [0.0, 1.0, 0.0, 39.875, 64000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 62250.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [28]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [29]:
from sklearn.preprocessing import LabelEncoder
ley = LabelEncoder()
y= ley.fit_transform (y)
print (y)

[0 1 0 0 1 1 0 1 0 1]


In [30]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 39.875, 54000.0],
       [0.0, 0.0, 1.0, 39.0, 62250.0],
       [0.0, 1.0, 0.0, 39.875, 64000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 62250.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [31]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [32]:
from sklearn.preprocessing import StandardScaler
std_sca= StandardScaler()
x_STD = std_sca.fit_transform(x)
print (pd.DataFrame(x_STD))


     0         1    2         3         4
0  1.0 -0.654654 -0.5  0.664912  1.002707
1  1.0 -0.654654 -0.5 -2.075331 -1.465494
2 -1.0  1.527525 -0.5  0.000000 -0.848444
3 -1.0 -0.654654  2.0 -0.141042  0.000000
4 -1.0  1.527525 -0.5  0.000000  0.179973
5  1.0 -0.654654 -0.5 -0.785805 -0.437077
6 -1.0 -0.654654  2.0 -0.141042 -1.054127
7  1.0 -0.654654 -0.5  1.309675  0.000000
8 -1.0  1.527525 -0.5  1.632056  2.133965
9  1.0 -0.654654 -0.5 -0.463423  0.488498


In [33]:
from sklearn.preprocessing import MinMaxScaler
Nm_x= MinMaxScaler()
x_NOR = Nm_x.fit_transform(x)
print (pd.DataFrame(x_NOR))




     0    1    2         3         4
0  1.0  0.0  0.0  0.739130  0.685714
1  1.0  0.0  0.0  0.000000  0.000000
2  0.0  1.0  0.0  0.559783  0.171429
3  0.0  0.0  1.0  0.521739  0.407143
4  0.0  1.0  0.0  0.559783  0.457143
5  1.0  0.0  0.0  0.347826  0.285714
6  0.0  0.0  1.0  0.521739  0.114286
7  1.0  0.0  0.0  0.913043  0.407143
8  0.0  1.0  0.0  1.000000  1.000000
9  1.0  0.0  0.0  0.434783  0.542857


In [35]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 39.875, 54000.0],
       [0.0, 0.0, 1.0, 39.0, 62250.0],
       [0.0, 1.0, 0.0, 39.875, 64000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 62250.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [34]:
from sklearn.preprocessing import Normalizer
Nm_x= Normalizer()
x_NOR = Nm_x.fit_transform(x)
print (pd.DataFrame(x_NOR))


          0         1         2         3    4
0  0.000014  0.000000  0.000000  0.000611  1.0
1  0.000021  0.000000  0.000000  0.000562  1.0
2  0.000000  0.000019  0.000000  0.000738  1.0
3  0.000000  0.000000  0.000016  0.000627  1.0
4  0.000000  0.000016  0.000000  0.000623  1.0
5  0.000017  0.000000  0.000000  0.000603  1.0
6  0.000000  0.000000  0.000019  0.000750  1.0
7  0.000016  0.000000  0.000000  0.000771  1.0
8  0.000000  0.000012  0.000000  0.000602  1.0
9  0.000015  0.000000  0.000000  0.000552  1.0


In [36]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 39.875, 54000.0],
       [0.0, 0.0, 1.0, 39.0, 62250.0],
       [0.0, 1.0, 0.0, 39.875, 64000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 62250.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [39]:
from sklearn.model_selection import train_test_split
train_test_split(x_NOR)

[array([[1.60642523e-05, 0.00000000e+00, 0.00000000e+00, 7.71084108e-04,
         9.99999703e-01],
        [0.00000000e+00, 0.00000000e+00, 1.92307638e-05, 7.49999789e-04,
         9.99999719e-01],
        [1.38888863e-05, 0.00000000e+00, 0.00000000e+00, 6.11110997e-04,
         9.99999813e-01],
        [1.72413762e-05, 0.00000000e+00, 0.00000000e+00, 6.03448166e-04,
         9.99999818e-01],
        [1.49253709e-05, 0.00000000e+00, 0.00000000e+00, 5.52238722e-04,
         9.99999847e-01],
        [2.08333300e-05, 0.00000000e+00, 0.00000000e+00, 5.62499911e-04,
         9.99999842e-01],
        [0.00000000e+00, 0.00000000e+00, 1.60642539e-05, 6.26505901e-04,
         9.99999804e-01]]),
 array([[0.00000000e+00, 1.85185135e-05, 0.00000000e+00, 7.38425724e-04,
         9.99999727e-01],
        [0.00000000e+00, 1.20481906e-05, 0.00000000e+00, 6.02409529e-04,
         9.99999818e-01],
        [0.00000000e+00, 1.56249970e-05, 0.00000000e+00, 6.23046754e-04,
         9.99999806e-01]])]

In [40]:
train_test_split (x_NOR,y,test_size = 0.2)

[array([[1.49253709e-05, 0.00000000e+00, 0.00000000e+00, 5.52238722e-04,
         9.99999847e-01],
        [1.60642523e-05, 0.00000000e+00, 0.00000000e+00, 7.71084108e-04,
         9.99999703e-01],
        [0.00000000e+00, 0.00000000e+00, 1.60642539e-05, 6.26505901e-04,
         9.99999804e-01],
        [0.00000000e+00, 1.56249970e-05, 0.00000000e+00, 6.23046754e-04,
         9.99999806e-01],
        [0.00000000e+00, 1.20481906e-05, 0.00000000e+00, 6.02409529e-04,
         9.99999818e-01],
        [0.00000000e+00, 0.00000000e+00, 1.92307638e-05, 7.49999789e-04,
         9.99999719e-01],
        [1.38888863e-05, 0.00000000e+00, 0.00000000e+00, 6.11110997e-04,
         9.99999813e-01],
        [1.72413762e-05, 0.00000000e+00, 0.00000000e+00, 6.03448166e-04,
         9.99999818e-01]]),
 array([[2.08333300e-05, 0.00000000e+00, 0.00000000e+00, 5.62499911e-04,
         9.99999842e-01],
        [0.00000000e+00, 1.85185135e-05, 0.00000000e+00, 7.38425724e-04,
         9.99999727e-01]]),
 array

In [41]:
train_test_split (x_NOR,y,test_size = 0.2)

[array([[1.72413762e-05, 0.00000000e+00, 0.00000000e+00, 6.03448166e-04,
         9.99999818e-01],
        [0.00000000e+00, 0.00000000e+00, 1.60642539e-05, 6.26505901e-04,
         9.99999804e-01],
        [1.49253709e-05, 0.00000000e+00, 0.00000000e+00, 5.52238722e-04,
         9.99999847e-01],
        [0.00000000e+00, 1.56249970e-05, 0.00000000e+00, 6.23046754e-04,
         9.99999806e-01],
        [0.00000000e+00, 0.00000000e+00, 1.92307638e-05, 7.49999789e-04,
         9.99999719e-01],
        [0.00000000e+00, 1.20481906e-05, 0.00000000e+00, 6.02409529e-04,
         9.99999818e-01],
        [1.60642523e-05, 0.00000000e+00, 0.00000000e+00, 7.71084108e-04,
         9.99999703e-01],
        [2.08333300e-05, 0.00000000e+00, 0.00000000e+00, 5.62499911e-04,
         9.99999842e-01]]),
 array([[1.38888863e-05, 0.00000000e+00, 0.00000000e+00, 6.11110997e-04,
         9.99999813e-01],
        [0.00000000e+00, 1.85185135e-05, 0.00000000e+00, 7.38425724e-04,
         9.99999727e-01]]),
 array

In [42]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split (x_NOR,y,test_size = 0.2)
print (pd.DataFrame(x_train), y_train)


          0         1         2         3    4
0  0.000014  0.000000  0.000000  0.000611  1.0
1  0.000021  0.000000  0.000000  0.000562  1.0
2  0.000000  0.000000  0.000019  0.000750  1.0
3  0.000000  0.000016  0.000000  0.000623  1.0
4  0.000015  0.000000  0.000000  0.000552  1.0
5  0.000000  0.000012  0.000000  0.000602  1.0
6  0.000000  0.000019  0.000000  0.000738  1.0
7  0.000017  0.000000  0.000000  0.000603  1.0 [0 1 0 1 1 0 0 1]
